apiVersion: apps/v1
kind: Deployment
metadata:
  name: eliminar-cliente-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eliminar-cliente
  template:
    metadata:
      labels:
        app: eliminar-cliente
    spec:
      containers:
        - name: parcial
          image: duvcy/parcial-microservicio:latest
          ports:
            - containerPort: 8080
