apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= # "password" en base64
  MYSQL_DATABASE: cGFyY2lhbA== # "parcial"
  MYSQL_USER: cm9vdA== # "root"
  MYSQL_PASSWORD: cGFzc3dvcmQ= # "password"
